### ISSUE TITLE
WaveGuard Console Error

### ISSUE THREAD

**Issue by DarkSlayer995** [WaveGuard-dev/Feedback#3]
Hey, I recently found a Console Error regarding WaveGuard, it rarely occurs, but it does exist, and it doesn't look like I'm the only one with the problem.

When starting the server, Waveguard loads at a certain point (with the following text)

[12:20:49 INFO]: [WaveGuard] Enabling WaveGuard v4.1.0*
[12:20:49 INFO]: []==========[WaveGuard-LicenseSystem]==========[]
[12:20:49 INFO]: >> Verifying your license...

Sometimes it takes a few minutes, and then you may get the error (See Pastebin link) → https://pastebin.com/3CSftZYJ

Another or similar error that a Discord member of WaveGuard has I'm not sure if this error is due to the plugin, I wanted to add it anyway. → https://i.imgur.com/Ca39J7M.png

Thanks for looking into it 
With kind Regards, xXGamerHDX

**Comment by GamingLPyt** [comment]
System is running, its a Connection Error from your Server, from which country is your server?

**Comment by DarkSlayer995** [comment]
Ignore this report you can close it I fixed it - Server Problem not WaveGuard's fault.
